Add support for new types and improve the expert mode attribute display
basysKom/opcua_browser pull request #14
Opened 2024-03-12 10:11 UTC by basyskom-jvoe

2024-03-12 16:36 UTC, khaexy requested changes

2024-03-12 16:36 UTC, khaexy commented on src/qml/BrowserView.qml
> +            color: Style.contextMenu.backgroundSelected
Each view has its own style element. It would therefore be better to extend the ThemeBrowserView element with popupBackground and popupTextColor.

2024-03-12 16:36 UTC, khaexy commented on src/qml/BrowserView.qml
> +                    color: Style.nodesView.textColor
see above

2024-03-12 16:36 UTC, khaexy commented on src/qml/BrowserView.qml
> +                    color: Style.nodesView.textColor
see above

2024-03-13 08:12 UTC, basyskom-jvoe commented on src/qml/BrowserView.qml
> +                    color: Style.nodesView.textColor
Done.

2024-03-13 08:12 UTC, basyskom-jvoe commented on src/qml/BrowserView.qml
> +                    color: Style.nodesView.textColor
Done.

2024-03-13 08:38 UTC, khaexy approved these changes

2024-03-13 08:38 UTC, merged