Add fallback for EnumValues decoding for servers that don't expose data type descriptions
basysKom/opcua_browser pull request #28
Opened 2024-03-27 09:37 UTC by basyskom-jvoe

2024-04-02 10:24 UTC, khaexy requested changes

2024-04-02 10:24 UTC, khaexy commented on src/opcuamodel.cpp
> +                                                    auto data = ext.encodedBody();
Besser anderen Namen wählen, da die data schon in der foreach-Schleife verwendet wird.

2024-04-08 06:59 UTC, basyskom-jvoe commented on src/opcuamodel.cpp
> +                                                    auto data = ext.encodedBody();
Done.

2024-04-08 07:21 UTC, khaexy approved these changes

2024-04-08 07:21 UTC, merged